services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - internal
      - external
    depends_on:
      - element
      - synapse
      - synapse-admin
    ports:
      - 8011:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/letsencrypt/live/

  element:
    image: vectorim/element-web:latest
    container_name: element
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./element/element-config.json:/app/config.json

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./matrix:/data

  synapse-admin:
    image: awesometechnologies/synapse-admin
    container_name: synapse-admin
    restart: unless-stopped
    environment:
      BASE_PATH: "/admin"
    networks:
      - internal
    volumes:
      - ./admin/config.json:/app/config.json

  coturn:
    image: instrumentisto/coturn:latest
    restart: unless-stopped
    ports:
      - 49160-49200:49160-49200/udp
      - 3478:3478
      - 5349:5349
    networks:
      - internal
      - external
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_SCHEDULE: 0 0 10 * * 1

networks:
  external:
  internal: