services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - internal
      - external
    depends_on:
     - element
     - synapse
     - synapse-admin
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


  element:
    image: vectorim/element-web:latest
    container_name: element
    restart: unless-stopped
    networks:
      - internal
    # ports:
    #   - 8001:80
    volumes:
      - ./element/element-config.json:/app/config.json

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    networks:
      - internal
    # ports:
    #   - 8002:8008
    volumes:
      - ./matrix:/data

  synapse-admin:
    image: awesometechnologies/synapse-admin
    container_name: synapse-admin
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 8999:80
    volumes:
      - ./admin/config.json:/app/config.json

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   networks:
  #     - internal
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /root/.docker/config.json:/config.json
  #   environment:
  #     WATCHTOWER_CLEANUP: true
  #     WATCHTOWER_ROLLING_RESTART: true
  #     WATCHTOWER_SCHEDULE: 0 0 10 * * 1

networks:
  external:
  internal:
  bridge:
    driver: bridge