services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/chat.conf:/etc/nginx/conf.d/chat.conf

  element:
    image: vectorim/element-web:latest
    container_name: element
    hostname: element
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./element/element-config.json:/app/config.json

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    hostname: synapse
    restart: unless-stopped
    ports:
      - 8002:8008
    volumes:
     - ./matrix:/data

  synapse-admin:
    image: awesometechnologies/synapse-admin
    container_name: synapse-admin
    hostname: synapse-admin
    restart: unless-stopped
    ports:
      - "8003:80"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_SCHEDULE: 0 10 * * MON